spring:
#  1,配置属数据源，
#  导入数据库驱动
#  在application.yml配置数据源相关信息
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.56.10:3306/mall_pms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false
        username: root
        password: root
    cloud:
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848
    application:
      name: product

mybatis-plus:
#  配置mybatis-plus
#  使用mapperscan
#  告诉mybatis plus 映射文件位置
  mapper-location: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 10000